version: '2'
services:

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lapsi
    volumes:
      - "./db:/var/lib/mysql"

  web:
    image: snimavat/django:latest
    container_name: web
    command: /bin/bash -c "python manage.py collectstatic --noinput --settings lapsi.settings.production && python manage.py makemigrations && python manage.py migrate && gunicorn lapsi.wsgi:application -b 0.0.0.0:8000"
    volumes:
     - ./app:/app
     - ./static:/static
    depends_on:
     - db
    expose:
     - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
     - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web



